### ISSUE TITLE
Deletion not happening

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#1018]
- [x] Make sure the bucket is deleted when deleting and archiving project @inaod568 
- [x] Regex in RemoveDir endpoint not matching anything that it should match --> not deleting @inaod568

**Comment by annefriedrich** [comment]
Hi, not sure if this is related, but I also cannot delete any documents with the following error message:

`Error: Failed to invoke event listener method HandlerMethod details: Bean [de.tudarmstadt.ukp.inception.search.SearchServiceImpl$$EnhancerBySpringCGLIB$$c5f26f5f] Method [public void de.tudarmstadt.ukp.inception.search.SearchServiceImpl.beforeDocumentRemove(de.tudarmstadt.ukp.clarin.webanno.api.event.BeforeDocumentRemovedEvent) throws java.io.IOException] Resolved arguments: [0] [type=de.tudarmstadt.ukp.clarin.webanno.api.event.BeforeDocumentRemovedEvent] [value=de.tudarmstadt.ukp.clarin.webanno.api.event.BeforeDocumentRemovedEvent[source=de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl@56b751b1]]`

  INCEpTION -- 22.4 (2022-02-15 20:51:43, build 4725783b)
