### ISSUE TITLE
Change `dds ls` size formats

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#1042]
@ewels: Have different units for each project by default (like `ls -lh`) but then have an option to list everything in one uni (like `ls -l`)

**Comment by ewels** [comment]
@MatthiasZepper may be able to implement a better solution

**Comment by ewels** [comment]
Will be resolved by https://github.com/ScilifelabDataCentre/dds_cli/pull/377

**Comment by inaod568** [comment]
Fixed in https://github.com/ScilifelabDataCentre/dds_cli/pull/410 
Improvement **_later_** to allow functionality as Matthias has started to implement.
