### ISSUE TITLE
Create page in web to link to pypi and releases

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#1098]
In the web, add a page with a link to https://pypi.org/project/dds-cli/ and also to the latest release (and thereby the executables) https://github.com/ScilifelabDataCentre/dds_cli/releases/latest

**Comment by inaod568** [comment]
@MatthiasZepper https://github.com/ScilifelabDataCentre/dds_cli/releases/latest

**Comment by ewels** [comment]
PR: https://github.com/ScilifelabDataCentre/dds_web/pull/1112
