### ISSUE TITLE
Add 3 unit admins to development setup -- can create projects without any additional fixes

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#1120]
Currently in development mode we always need to set the unit users as unit admins before being able to create a project. To simplify further development, we need to add 3 unit admins to the development database.

Involves adding new users to the `db_init` file.

**Comment by zishanmirza** [comment]
Fixed in #1142.

**Comment by zishanmirza** [comment]
Fixed in #1142.

**Comment by zishanmirza** [comment]
Fixed in #1142.

**Comment by zishanmirza** [comment]
Fixed in #1142.
