### ISSUE TITLE
Cronjob: Clean up invites which are not answered after a week

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#1137]
Go to the `scheduled_tasks.py` module and follow the structure in the other cron jobs.

1. Loop through the invites
2. Check when it was issued
3. Remove those entries that are older than 7 days
(Double check that this also removes the corresponding rows in the ProjectInviteKeys table)

**Comment by zishanmirza** [comment]
Fixed in #1147.

**Comment by zishanmirza** [comment]
Fixed in #1147.

**Comment by zishanmirza** [comment]
Fixed in #1147.
