### ISSUE TITLE
Database Isolation

### ISSUE THREAD

**Issue by senthil10** [ScilifelabDataCentre/dds_web#291]

**Comment by senthil10** [comment]
Have created SQL schema to create tables, but isolating the DB for just table creation is not super optimal. Should look into how the database updates/migrations need to be handled in case it changes after a stable version. Since the current DB is too floating now, maybe a good idea to wait until the system is quite stable. Then look into creation/update/migration of DB and isolate it if necessary.

**Comment by inaod568** [comment]
Since this is actually planned, this should not be in the Icebox column. Moving to `Product Backlog`.

**Comment by inaod568** [comment]
If this is in progress it should be in the `In Progress` column.

**Comment by inaod568** [comment]
Closing this in favour of new migrations card
