### ISSUE TITLE
Facilities: modify files through front-end

### ISSUE THREAD

**Issue by ewels** [ScilifelabDataCentre/dds_web#457]
Potentially also rename / change the file path too? But that's probably trickier and less important.

**Comment by senthil10** [comment]
Updated the card as the delete stuff is already have a card #413 :)

**Comment by inaod568** [comment]
> Potentially also rename / change the file path too? But that's probably trickier and less important.

Rename/change file path shouldn't be that difficult. Modifying the files though - once up in the cloud, they can't be edited there, instead they have to be removed, edited and then uploaded again. So I think that would be a greater challenge.

**Comment by ewels** [comment]
Hmm, maybe we keep things simple and just say that files have to be deleted and re-uploaded.

Ability to rename files could be a nice addition, but low priority.

Fine by me to close this issue. To be completely honest, I can't really remember what my motivation was when I wrote it. I think that we have bigger fish to fry...

**Comment by inaod568** [comment]
Yeah, we can move this to Icebox maybe. 👍🏻

**Comment by inaod568** [comment]
I think we can keep this in the `Icebox` column 👍🏻

**Comment by inaod568** [comment]
Ok looking through the board now and I think we can remove this. Now we have said that files will only be possible to overwrite if the project has not already been marked as Available previously. In the future, if we have nothing else to fix and this is still a suggestion, we can have a look. But in that case only non-sensitive projects.
