### ISSUE TITLE
Uploading files via web is not registering all files

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_web#460]
When uploading a file with a large number of files (tested with ca 14 000 files), the web uploader is capped at around 1500 files. I don't know why...

**Comment by alneberg** [comment]
Suggested solution: https://github.com/ScilifelabDataCentre/dds_web/pull/459#issuecomment-854100297

**Comment by ewels** [comment]
Added a warning about this, not expecting people to use the web uploader for large projects so this is hopefully sufficient for the short-term.

**Comment by inaod568** [comment]
Not applicable at this time.
