### ISSUE TITLE
Fix broken page when uploaded file size is zero

### ISSUE THREAD

**Issue by senthil10** [ScilifelabDataCentre/dds_web#463]
For some reason, if a project have files uploaded but they are 0 in size, it will break the project page for the users. This is because there is a condition loop in the `project.html` template, that checks the project size to decide if it can render the download button or not. But the project size information is passed in `project.py` script to the template only if the project size is bigger than 0

**Comment by inaod568** [comment]
Removing this since web is deactivated.
