### ISSUE TITLE
Import and use CLI module directly

### ISSUE THREAD

**Issue by senthil10** [ScilifelabDataCentre/dds_web#464]
Currently for upload and download CLI is called via sub process in the backend, rather it would be better to import the CLI's modules directly and use them

**Comment by inaod568** [comment]
Changing this from `must have` to `should have` since it's not vital for NGI to have a working upload via web interface and now we need to prioritize the vital parts of the system during the fall.

**Comment by inaod568** [comment]
Need to disable upload and download via web though since it does not use the functions and also uses insecure functions to make the access work during upload and download. Creating a new card for this.
