### ISSUE TITLE
Add arbitrary metadata for projects

### ISSUE THREAD

**Issue by ewels** [ScilifelabDataCentre/dds_web#510]

**Comment by ewels** [comment]
Different facilities will probably want to assign different metadata to projects. For example, additional identifiers to tie to internal systems, labels, and so on.

Suggestion is that we allow facilities to create arbitrary key:value metadata pairs for any project.

* Available keys should be set at facility level, for all projects (maybe?)
* Facilities should be able to choose whether a given key is visible to the end user or not
* Should be possible to search / filter projects for a given key / value.

**Comment by inaod568** [comment]
Moving to Jira.
