### ISSUE TITLE
Simplified config setup 

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_web#561]
It should be possible to run `docker compose run` directly without creating any extra config files. Just as it says in the README.

**Comment by inaod568** [comment]
Is this the cleanup you did the other day? Also, is this `must have`, `should have` or `could have`?

**Comment by inaod568** [comment]
@alneberg

**Comment by alneberg** [comment]
Yes this should be closed with the PR https://github.com/ScilifelabDataCentre/dds_web/pull/564 . Should I tag the issues in the PRs or just remember to close the issues when the PR is merged? I guess it's a should have, but I have no idea what the definitions for those are.

**Comment by inaod568** [comment]
You can tag or manually move the ones you remember. If there's someone left at some point then I will probably find it and just check the status of it. 👍🏻 So it's up to you. I vary a bit, depending on the card

**Comment by inaod568** [comment]
The `must have` etc are defined in the Wiki: https://github.com/ScilifelabDataCentre/dds_web/wiki/Scrum-Board-Guidelines 
Basically must haves are the ones we should be working on, then should haves when they're done and then could haves 👍🏻
