### ISSUE TITLE
Add function to create the db tables but not fill them 

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#587]
Before the next dev deployment we need to have another function which just calls the `db.create_all()`, without actually filling the database tables. Currently the db is filled with info publicly available on GitHub, including the passwords. Emptying the database in the dev deployment for now.

**Comment by alneberg** [comment]
Apparently the `db.create_all()` method does nothing to tables that already exists so it seems fairly safe to run it by default:

https://github.com/pallets/flask-sqlalchemy/blob/25edfae1835f0ac70483cb38e0d83d3f00aeb208/src/flask_sqlalchemy/__init__.py#L1044-L1048
```
def create_all(self, bind="__all__", app=None):
    """Create all tables that do not already exist in the database.
        This does not update existing tables, use a migration library
        for that.
```

But as it states, if the tables exists but are different than what the model states, this will still not do anything.

**Comment by inaod568** [comment]
Yes 👍🏻 Great
