### ISSUE TITLE
Figure out what is needed to secure frontend

### ISSUE THREAD

**Issue by worukan** [ScilifelabDataCentre/dds_web#693]
https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#token-structure

includes additional information to secure the token in browser, some flags are needed and perhaps a bit of addition in the token. These can be investigated and implemented later when the web front-end is about to come up.

- XSRF  / CSRF

**Comment by alneberg** [comment]
We currently don't use the authentication token in the frontend at all, so this issue is either quite big or it might need to be adapted to what we currently have.

**Comment by zishanmirza** [comment]
There is already a CSRF token implemented. However, I could not find CSP that was set.

**Comment by inaod568** [comment]
Closing this, we need to create other cards that are less broad, but we can wait until continuing with the web development.
