### ISSUE TITLE
Do we have an Intrusion Detection System or something similar?

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#702]
![image.png](https://images.zenhubusercontent.com/60190598ba808fccea954870/449e5cb5-807b-43dc-b62c-2021f5f06538)

**Comment by inaod568** [comment]
Have asked Hamza.

**Comment by inaod568** [comment]
No, we do not.

**Comment by inaod568** [comment]
@talavis Thoughts?

**Comment by talavis** [comment]
We have no such things set up, and I do not plan to add it either. My hope is to have full logging after the cluster redesign, but that's it.

**Comment by inaod568** [comment]
Checking with IT-sec.
