### ISSUE TITLE
Delete user / user info

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#703]
![image.png](https://images.zenhubusercontent.com/60190598ba808fccea954870/787fac29-33ed-4be5-825c-8422e6882595)

**Comment by MatthiasZepper** [comment]
In the user roles we currently list _Remove themselves_ permission for every role. But I guess this refers to the project associations?

Should any user be able to delete their own DDS user account? Or should only unit users be able to delete accounts? Do we want to have some kind of approval system, e.g. an e-mail which contains a link that needs to be clicked to confirm the deletion or a 2FA token?
