### ISSUE TITLE
Unfreeze version numbers

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_web#779]
Currently all packages are installed with exact version. I think it can be a potential security issue if we don't stay up to date with the patched releases of different packages. There might be a reason to freeze versions used in production however so we know which versions are actually used. Sorry for confusing issue description.

**Comment by inaod568** [comment]
Going with the following motivation and the changes that @talavis has already made: https://github.com/ScilifelabDataCentre/dds_web/pull/797#issuecomment-1028983846
