### ISSUE TITLE
User Invitation endpoints: Token creation and handling issues 

### ISSUE THREAD

**Issue by MatthiasZepper** [ScilifelabDataCentre/dds_web#785]
In its current form, there are multiple issues with the token handling of the _User Invitation endpoints_ that should be reconsidered and (possibly) changed: 

**Main problem:**  
 
https://github.com/ScilifelabDataCentre/dds_web/blob/427bbf744caf9a24eb3feba6b31b8b85f85a5c05/dds_web/web/user.py#L81-L90

When the `try` fails, there is no `invite_row` to be deleted. It is unfortunate that `email`, which is extracted from the token, is currently our only means to select the corresponding invite row. 

Currently, I see two ways of addressing this issue:

1. We add an additional column to the database, which stores a hash of the token that is being sent out with the invite. In case one of the exceptions is raised, the `invite_row` to be deleted is selected via the hash and not the token's contents.
2. We make use of the [payload method, that the exceptions provide](https://itsdangerous.palletsprojects.com/en/2.0.x/exceptions/): In the example above, the contents of the token should be accessible via the `signerr.payload` even though the exception was raised. This would however require changes to the token, since we currently do not embed the email in the token's payload.  

**Accessory problem:**

While investigating the feasibility of the second approach, I noticed that the invite token [is malformed according to JWT standards](https://datatracker.ietf.org/doc/html/rfc7519#section-7.2). When pasting e.g. this sample token

```Imlfc2hvdWxkX2JlX3NlY3JldEBzY2lsaWZlbGFiLnNlIg.YfPhdw.ebptv6tvs4dB89npFffeRzUDV0g``` 

to [JWT.io](https://jwt.io/), it becomes evident, that the e-mail address is embedded in the header of the token instead of the payload. The header is also not a valid JSON, but a mere string. The invited e-mail can also be read openly.

Therefore, I propose to embed the invited e-mail in the token's payload instead of the header and possibly switch to an encrypted invite token as well. This will likely anyway be of relevance when we embed a temporary key into the invite later and would allow us to make use of the `Exception.payload` method to solve the main problem as stated above.

**Minor problem:**

The salt for the UserDeletion and UserInvite endpoints is hard-coded. We might want to turn this into a config value? 

https://github.com/ScilifelabDataCentre/dds_web/blob/427bbf744caf9a24eb3feba6b31b8b85f85a5c05/dds_web/api/user.py#L178

**Heads up!**

The User Deletion endpoint was modeled after the Invite Endpoint. Therefore, those issues also exist with the User Deletion endpoint - except for the first one, which can be circumvented there by getting the `e-mail` of the currently logged in user instead of extracting it from the token.

**Comment by inaod568** [comment]
The token things are handled in a few of the different ongoing PRs and tasts, such as #827, should make sure it all works as it should there.
