### ISSUE TITLE
Add cronjobs

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#791]
Add the scheduled jobs that would be useful to have in the system. 

@talavis mentioned that it should be easy to run cron jobs on a schedule with kubernetes. In that case we would write separate scripts for the different tasks. Need to make sure we can access all the information needed though.

- [x] Health check -- the items in the database are located in the cloud, and vice versa
- [x] Move projects between different statuses e.g. "expired"
- [ ] Clean up log files?
- [ ] Remove invites that were not accepted after one week

**Comment by inaod568** [comment]
S3 / database health check

**Comment by talavis** [comment]
Optional: clean up logs older than 12 months every month

**Comment by inaod568** [comment]
Clean up password reset?

**Comment by inaod568** [comment]
Closing. Adding more specific items if needed.
