### ISSUE TITLE
MFA_EXPIRES_IN variable vs Token expiration

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_web#793]
With the implementation of MFA through hotp, the token is invalid and returns an authentication error if the mfa has expired (MFA_EXPIRES_IN) or if the token itself has expired (set in the code, default 48 hours). Currently whatever time is set to the lowest will determine the expiration time.

I think it would be good if we would be able to have two different expiration times in place at once so that:
1. Sensitive operations are only permitted if mfa has not expired (48 hours sounds good to me)
2. Any other operation is still permitted as long as the token has not expired (Could be 7 days maybe?)

But I don't have a clear idea how to implement this.

**Comment by inaod568** [comment]
Would 48 hours be enough for uploading/downloading sensitive information via the CLI? Thinking also of scheduling.

**Comment by inaod568** [comment]
Moving to Jira.
