### ISSUE TITLE
A user cannot be told  if an hotp has expired

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_web#794]
The user will currently get an "Invalid Token" message.

If a user sends an expired hotp to the `second_factor` endpoint, the token authentication will trigger a new hotp value to be issued before attempting to validating the submitted hotp value. Therefore the `hotp_issue_time` is updated and so is the `hotp_counter`. So when the submitted hotp value is validated, it's invalid due to the updated counter.

I think it would be nice to be able to tell the user that it has been too long since the token was issued.

**Comment by inaod568** [comment]
Moving to Jira.
