### ISSUE TITLE
Use flask.session cookie instead of regular cookie

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_web#795]
Flask uses a signed cookie for its session, so it can't be tampered with:

(Old version: https://flask.palletsprojects.com/en/1.1.x/api/?highlight=session#sessions)
New: https://flask.palletsprojects.com/en/2.0.x/api/#sessions

So if we put an encrypted token in the session instead of a cookie we can be sure it was the server that put the token there in the first place and we won't offer any entry for a user to submit any token.

**Comment by alneberg** [comment]
This is not completely covered by using flask.session for the registration. We still use a cookie for the 2fa confirmation.

**Comment by inaod568** [comment]
NOW it's actually done
