### ISSUE TITLE
Set memory_cost config for development purposes

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#812]
https://github.com/ScilifelabDataCentre/dds_web/pull/809#discussion_r799529528

**Comment by talavis** [comment]
Adding my comment here as well:

Memory cost is in kibibytes, so memory_cost=4194304means that you want to use 4GiB of RAM. In the case of my docker setup, that's beyond my resource limits. Personally I also think it's better to list such numbers as hex, ie. 0x400000. So much clearer what they represent.

What should the default value be?

**Comment by worukan** [comment]
4GiB of RAM in production. It could be low as a few hundreds of MiB for a development environment.

**Comment by inaod568** [comment]
Yep it was in my PR before but we decided to go with Volkans that we just merged. The `memory_cost` will show up in the coming PRs so it's fine that we add this now even when it's not  in the dev branch yet
