### ISSUE TITLE
Invite user to multiple projects at the same time

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#860]
At this time, https://github.com/ScilifelabDataCentre/dds_web/pull/855 and https://github.com/ScilifelabDataCentre/dds_web/pull/863 add to and change the functionality of the invites and how inviting new users  / adding existing users to projects should work. With these changes, a user can invite a user to one project at a time.

**Needed functionality: ** To invite a _new user_ to multiple projects at one time. 

At some point we should also be able to invite a user to multiple projects with different roles, e.g. a user could be a Researcher for one and a Project Owner for another. Adding this functionality is not a high priority but a should have. 

However, adding users to multiple projects at a time is **required**.

**Comment by inaod568** [comment]
@MatthiasZepper Is this the card you're working on at the moment? Or something else?

**Comment by alneberg** [comment]
Fixed with #911.
