### ISSUE TITLE
Create a new endpoint for providing project access to a user

### ISSUE THREAD

**Issue by worukan** [ScilifelabDataCentre/dds_web#877]
When a user needs to reset password, project user keys have to be re-established. Roles from Project Owner and above can invite to project which means that they can `share_project_private_key`. The flow for this activity has to be defined clearly. When can this endpoint be used? How is the interaction initiated? How would for example a unit personnel know to use this and when? Do we need to store the information about a reset password and/or how and who to propagate this information? A researcher can be involved in multiple projects requiring interaction with multiple units/project owners. Do we need to send email about the user to all involved?
Thinking of _if it is a unit user, it would be only unit projects, and if it is a research user, it would be the projectusers entries_ , we could check which projects are defined in the db but not having projectuserkeys entries in the table, if we immediately clean up that table at password reset. Does this make sense?
This is related to #876 in a way that first reset password happens and then someone has to use this endpoint to share project keys to the user.
In terms of security parts, we already have everything ready, I think.

**Comment by MatthiasZepper** [comment]
See more extensive suggestion written in #876. 

To initiate the endpoint, a sufficiently privileged user would enter `dds project access fix` or alike and project access would be reestablished for the specified e-mails and/or projects.

I would not delete the keys right away, but move them to a _Lost/Orphaned Keys_ table. Then the `fix` command could replace those keys after which they are deleted for good.

**Comment by inaod568** [comment]
Merged with #885
