### ISSUE TITLE
Adressing logging for so far uncaught exceptions

### ISSUE THREAD

**Issue by MatthiasZepper** [ScilifelabDataCentre/dds_web#949]
We currently have an issue with some uncaught exceptions, which will not produce helpful logging messages for trouble-shooting. For that reason, I will try to modify the logging accordingly to address those.

**Comment by inaod568** [comment]
In that case it's the general logger right? Not the action logger.

**Comment by inaod568** [comment]
@MatthiasZepper 
Ah thanks for the slack link! 
Now I'm up to speed. Yes, what you and Phil suggested would work.

**Comment by inaod568** [comment]
Fixed with #958
