### ISSUE TITLE
Add `/motd` endpoint

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#986]
Message of the day to inform users about updates, down time etc. 

Also, of course, combined with a slack channel where we inform the users so that it doesn't distrupt major uploads / downloads etc. 

1. Create table in models.py: "MOTD" for example
2. Endpoint with post method -- `dds_web/api/unit.py` (and add to `dds_web/api/__init__.py`) - should only be available Super Admin
3. Create `dds` cli command for updating motd

**Comment by talavis** [comment]
I can see a couple of ways of managing this one depending on who we want to set it.
* Only about planned downtime and similar things:
  - Set by admin in an environment variable
* May also inform about other things
  - Set by admin in an environment variable

**Comment by inaod568** [comment]
It's great with some comments here, such as those you're adding 👍🏻  just clarifying that the cards in the Product Backlog will be worked after we're done with the ones in the Sprint Backlog
