### ISSUE TITLE
`dds ls --usage --sort usage` does not work

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_web#992]
Apparently it doesn't work. Just make sure it does and in that case just close. Also make sure that the sort function takes the size format (e.g. GB, MB etc) into account and not just the number.

**Comment by MatthiasZepper** [comment]
While working on the [CLI PR377](https://github.com/ScilifelabDataCentre/dds_cli/pull/377), I have extensively tested the sort functionality and not encountered any issues. Importantly, [sorting happens on the raw byte values and prior for formatting the API response for the table rendering.](https://github.com/ScilifelabDataCentre/dds_cli/blob/4e662595e9dcc72cdbba7145fb9615754c9ff52f/dds_cli/data_lister.py#L121-L128) Hence, this functionality should (and is) not be affected by the unit prefixes.

**Comment by inaod568** [comment]
Great, thanks!
